### ISSUE TITLE
[GW170817] Time of radio point probably incorrect

### ISSUE THREAD

**Issue by omsharansalafia** [astrocatalogs/kilonovae#1]
A VLA radio point is given at MJD=58031.28, with a flux density of 34 uJy @ 3 GHz. That MJD corresponds to the 5th of October, but a quick look at the source paper (Hallinan et al.) shows that the latest radio point is on the 17th of September. I suggest to change the MJD value to 58013.67, which should match the Sep 17.75 value given in Hallinan et al.

**Comment by guillochon** [comment]
Thanks for pointing this out @omsharansalafia! There were a couple more times for the radio observations that were also mis-entered. The radio data should now been fixed.
