### ISSUE TITLE
[GW170817] Broken reference: [34]

### ISSUE THREAD

**Issue by korobkin** [astrocatalogs/kilonovae#3]
The reference [34] Nicholl, Guillochon & Berger (2017) is listed as a source for GW170817. Although this is a brilliant work, it never mentions GW170817 -- perhaps because it was published before the event occurred. This reference is listed in the front page for GW170817 in the Data > Aliases section, as well as a source for many optical and IR data, which is confusing. Perhaps [28] Nicholl et al. (2017) is meant instead.

**Comment by guillochon** [comment]
Hi @korobkin,

Actually that reference is used (indirectly) because the kilonova model implemented by @villrv uses some code from it, it's attached to the model data attached to the event.

**Comment by korobkin** [comment]
Hi @guillochon,

Thanks for the quick reply! Sorry for the confusion. I was actually trying to find a source for this observation:
{u'e_magnitude': u'0.230761307292', u'telescope': u'Gemini-S', u'instrument': u'FLAMINGOS-2', u'time': u'58011.969', u'system': u'AB', u'band': u'Ks', u'magnitude': u'22.1234097901', u'u_time': u'MJD', u'realization': u'3', u'model': u'2', u'source': u'34'}

This is one of the photometry entries in the big json file downloadable from the front page. As you can see, it uses '34' as a reference, but this is actually a different paper.

**Comment by guillochon** [comment]
Hi @korobkin, the attributes on that photometry entry tell you that it’s actually generated from the model: `realization`, `model`, so not a real observation. Apologies for the confusion.
